### ISSUE TITLE
SVG has random lines from top left corner if you double tap 

### ISSUE THREAD

**Issue by andrewmoreau1996** [ww6015132/SilkySignature#6]
So when I was doing some testing I found that if you double tap to form a dot for an ' i ' and drag a little or draw to the full edge of the signature pad, the SVG version will shoot lines from the upper left corner in landscape mode(not sure about portrait mode). But it should be noted that there are no unexpected lines in the bitmap version.  I have attached 2 sigs to show what I was talking about.

P.S. I had to zip them because GitHub doesn't like bitmaps and SVG's 

[sigs.zip](https://github.com/ww6015132/SilkySignature/files/1035103/sigs.zip)

**Comment by ww6015132** [comment]
Thanks for this. I find out the problem.
This bug would be fixed on version 0.0.9.
I will release it today or tomorrow

Thanks!
