### ISSUE TITLE
only dot not working.

### ISSUE THREAD

**Issue by attaullahpro** [ww6015132/SilkySignature#8]
if i want to put dot . (mean single touch) on signature-pad then dot not working for dot we must be move/drag then working. please enable functionality for touching and adding dot "."

**Comment by ww6015132** [comment]
This should work. You don't have to drag. The logic is, when your drag distance is longer than 3 pixel something would be draw.

**Comment by attaullahpro** [comment]
please, resolve [this issue](https://github.com/ww6015132/SilkySignature/issues/7) as well thanks

**Comment by attaullahpro** [comment]
still, I tried dot. without dragging it's not working, 
and please, resolve [this issue](https://github.com/ww6015132/SilkySignature/issues/7) as well thanks

**Comment by chnouman** [comment]
same
